- name: Allow traffic on ports 80 and 8080 on centos
  firewalld:
    port: "{{ item }}/tcp"
    zone: public
    state: enabled
  with_items:
    - 80
    - 8080
  when: ansible_os_family == 'RedHat'
